/**
 * Lifecycle statuses of a photo session.
 * Transitions are managed exclusively by the Application Layer.
 */
export enum SessionStatus {
    CREATED = 'CREATED',
    PHOTOGRAPHER_PENDING = 'PHOTOGRAPHER_PENDING',
    PHOTOGRAPHER_CONFIRMED = 'PHOTOGRAPHER_CONFIRMED',
    SHOOTING_COMPLETED = 'SHOOTING_COMPLETED',
    RETUSH_IN_PROGRESS = 'RETUSH_IN_PROGRESS',
    RETUSH_COMPLETED = 'RETUSH_COMPLETED',
    PRINT_IN_PROGRESS = 'PRINT_IN_PROGRESS',
    PRINT_COMPLETED = 'PRINT_COMPLETED',
    READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
    DELIVERED = 'DELIVERED',
}
